const Pics = [
    './Images/IMG1.jpg', 
    './Images/IMG2.jpeg', 
    './Images/IMG3.jpeg', 
    './Images/IMG4.jpeg', 
    './Images/IMG5.jpeg', 
    './Images/IMG6.jpeg', 
    './Images/IMG7.jpeg', 
    './Images/IMG8.jpeg', 
    './Images/IMG9.jpeg', 
    './Images/IMG10.jpeg', 
    './Images/IMG11.jpeg', 
    './Images/IMG12.jpeg', 
    './Images/IMG13.jpeg', 
    './Images/IMG14.jpeg', 
    './Images/IMG15.jpeg',
    './Images/IMG16.jpeg', 
    './Images/IMG17.jpeg', 
    './Images/IMG18.jpeg', 
    './Images/IMG19.jpeg', 
    './Images/IMG20.jpeg', 
    // './Images/IMG21.jpeg', 
    './Images/IMG22.jpeg', 
    './Images/IMG23.jpeg', 
    './Images/IMG24.jpeg', 
    './Images/IMG25.jpeg', 
    './Images/IMG26.jpeg', 
    './Images/IMG27.jpeg', 
    './Images/IMG28.jpeg', 
    './Images/IMG29.jpeg', 
    './Images/IMG30.jpeg',
    './Images/IMG31.jpeg', 
    './Images/IMG32.jpeg', 
    './Images/IMG33.jpeg', 
    './Images/IMG34.jpeg', 
    './Images/IMG35.jpeg', 
    './Images/IMG36.jpeg', 
    './Images/IMG37.jpeg', 
    './Images/IMG38.jpeg', 
    './Images/IMG39.jpeg', 
    './Images/IMG40.jpeg', 
    './Images/IMG41.jpeg', 
    './Images/IMG42.jpeg', 
    './Images/IMG43.jpeg', 
    './Images/IMG44.jpg', 
    './Images/IMG45.jpg',
    './Images/IMG46.jpg', 
    './Images/IMG47.jpg', 
    './Images/IMG48.jpg', 
    './Images/IMG49.jpeg', 
    './Images/IMG50.jpg', 
    './Images/IMG51.jpg',
    './Images/IMG52.jpg'

]

export default Pics;